### ISSUE TITLE
Best practices

### ISSUE THREAD

**Issue by jbants** [stactools-packages/nrcan-landcover#14]
**Describe the bug**
Following [best practices](https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#static-catalogs), the STAC collection should be `collection.json`

**To reproduce**
`scripts/stac nrcanlandcover create-collection -d ./examples/collection.json`

**Expected behavior**
STAC collection should be `collection.json`

**Additional context**
https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#static-catalogs

**Comment by cuttlefish** [comment]
`-d` takes a directory, not a filename.
But it does produce an incorrect name.
